apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: slow-server
data:
  config.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      
    common:
      path_prefix: /data
      storage:
        filesystem:
          chunks_directory: /data/chunks
          rules_directory: /data/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
          
    compactor:
      working_directory: /data/compactor
      
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      wal:
        dir: /data/wal
        
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
            
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/index
        cache_location: /data/boltdb-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/chunks
        
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    
    ruler:
      storage:
        type: local
        local:
          directory: /data/rules
      rule_path: /tmp/rules
      alertmanager_url: http://alertmanager:9093
      ring:
        kvstore:
          store: inmemory
      enable_alertmanager_v2: true 